version: '2'

services:
        redis:
                image: redis:5.0.4-alpine
                volumes:
                - ${PWD}/tmp/data:/data
                ports:
                - "6379:6379"
                container_name: "redis"
        mosquitto:
                image: jllopis/mosquitto:v1.6.8
                container_name: "mosquitto"
                volumes:
                - /tmp/mosquitto/var/lib/mosquitto:/var/lib/mosquitto
                - ${PWD}/mosquitto.conf:/etc/mosquitto/mosquitto.conf
                ports:
                - "1883:1883"
                - "8883:8883"
                - "9883:9883"
                environment:
                - DOMAIN=example.local
                - PORT=8080
                links:
                - redis
                depends_on:
                - redis
                labels:
                - "local.example.description=Mosquitto v1.6.8 MQTT server"

